[project]
name = "MangaDM"
dynamic = ["version"]
description = "A tool for downloading manga."
authors = [{ name = "xMohnad" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"

dependencies = [
  "aiohttp>=3.12.13",
  "dacite>=1.9.2",
  "ebooklib>=0.19",
  "inquirerpy>=0.3.4",
  "pyyaml>=6.0.2",
  "rich>=14.0.0",
  "typer>=0.19.2",
]

classifiers = [
  "Environment :: Console",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Terminals",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/xMohnad/MangaDM"
Issues = "https://github.com/xMohnad/MangaDM/issues"

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "mangadm.__version__" }

[tool.hatch.build.targets.wheel]
packages = ["src/mangadm"]

[project.scripts]
mangadm = "mangadm.cli:app"

[tool.uv]
package = true

[tool.pyright]
reportUnusedCallResult = false

[tool.ruff]
line-length = 120

[dependency-groups]
dev = ["codespell>=2.4.1", "ruff>=0.12.9", "ptpython>=3.0.0"]
