name: Deploy and Release

on: [push]

permissions:
  contents: write
  id-token: write

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build twine
          pip install -r requirements.txt

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(python -c "import mangadm; print(mangadm.__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Build the package
        run: python -m build --no-isolation

      - name: List dist directory
        run: ls -l dist/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*.tar.gz,dist/*.whl
          tag: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Check distribution's long description rendering on PyPI
        run: twine check dist/*

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
