name: Build and Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build toml

      # 4. Extract version from the package
      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(python -c "import mangadm; print(mangadm.__version__)" )
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      # 5. Show the extracted version
      - name: Show version
        run: echo "Version: ${{ env.VERSION }}"

      # 6. Build the Python package
      - name: Build the package
        run: python -m build

      # 7. Upload the built package as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-package
          path: dist/

      # 8. Publish the package to PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      # 9. Create a GitHub Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          artifacts: dist/*.tar.gz, dist/*.whl
